---
language: node_js
node_js:
  - 4
  - 6
  - 7
  - 8
  - 9
  - 10

sudo: false

cache:
  yarn: true

install:
  - yarn install --no-lockfile

script:
  - yarn test

after_success:
  - |
    if [[ "$TRAVIS_NODE_VERSION" = "8" ]] ; then
      echo "Pushing to Coveralls..." >&2
      yarn coveralls
    else
      echo "Not pushing to Coveralls."
    fi
